Adding Java builds to the repository
pulumi/pulumi-azure-native pull request #1920
Opened 2022-08-18 14:14 UTC by stack72

We are not checking in the generated sources here but we do ensure
that the gradle files are available to check on the dependencies

2022-08-18 14:17 UTC, t0yv0 commented
🤞  curious to see build times on Java build.

2022-08-18 14:18 UTC, t0yv0 approved these changes

2022-08-18 16:33 UTC, myhau commented
Are you sure [this schema](https://github.com/pulumi/pulumi-azure-native/pull/1920/files#diff-545ff4fc09480bc4d71134270a4ab338e66251db350f31defeea5ad12ebbf017) was generated by `pulumi-gen-azure-native` with `pulumi-java` version bumped to `v0.5.x` (not `v0.2.0`)? 

I'm asking, because an issue that I've been investigating (https://github.com/pulumi/pulumi-java/issues/808) seems to be fixed in `pulumi-java` `v0.5.x`, but `schema.json` in this PR still contains invalid Java examples (try  `gron schema.json | grep -i 'resources["azure-native:keyvault:Vault"].description'` and then `cmd+f` for `Map.of`). 

I also checked this locally by building this PR (cmd tools + doc schema) — examples are fine, issue is not there.

2022-08-18 18:45 UTC, stack72 commented
> @stack72
> 
> Are you sure [the `schema.json` file](https://github.com/pulumi/pulumi-azure-native/pull/1920/files#diff-545ff4fc09480bc4d71134270a4ab338e66251db350f31defeea5ad12ebbf017) was generated by `pulumi-gen-azure-native` with `pulumi-java` version bumped to `v0.5.x` (not `v0.2.0`)?
> 
> I'm asking, because an issue that I've been investigating ([pulumi/pulumi-java#808](https://github.com/pulumi/pulumi-java/issues/808)) seems to be fixed in `pulumi-java` `v0.5.x`, but `schema.json` in this PR still contains invalid Java examples (try `gron schema.json | grep -i 'resources["azure-native:keyvault:Vault"].description'` and then `cmd+f` for `Map.of`).
> 
> I also checked this locally by building this PR (cmd tools + doc schema) — examples are fine, issue is not there.

Hi @myhau 

The schema is generated using v0.5.0 of pulumi-java dependency - should it be a different version?

2022-08-18 23:06 UTC, t0yv0 commented
https://github.com/pulumi/pulumi-azure-native/runs/7908286955?check_suite_focus=true#step:18:39

Building java in 6s -too good to be true? Something is not building.

2022-08-18 23:11 UTC, stack72 commented
> https://github.com/pulumi/pulumi-azure-native/runs/7908286955?check_suite_focus=true#step:18:39
> 
> Building java in 6s -too good to be true? Something is not building.

I can pass verbose flags to gradle if you want - this is the same behaviour I get locally 

the build is super fast for me but the generation is slower

2022-08-18 23:12 UTC, stack72 commented
(But not 6 seconds!)

2022-08-22 17:27 UTC, t0yv0 commented
I've tried on my machine. After `cd sdk/java` I run `gradle build` and it's running for 1m53s now and still going. With Java compiler hogging CPU. That's what I'd expect.

However when I run the `make build_java` it exists immediately.

Something is fishy.

2022-08-22 17:29 UTC, t0yv0 commented
OK so `--version` argument makes Gradle print a version and exit, instead of building! That's the problem I think

2022-08-22 17:33 UTC, t0yv0 commented
Perhaps

```
build_java:: $(WORKING_DIR)/sdk/java/go.mod .version
	cd ${PACKDIR}/java/ && \
	 	gradle --console=plain -Pversion=$(shell cat .version) build

```

2022-08-22 18:41 UTC, t0yv0 requested changes
Would love to see Java builds actually building, see above. TYVM.

2022-09-01 15:18 UTC, t0yv0 commented on Makefile
> +		gradle --console=plain build --version $(shell cat .version)
Still passing --version incorrectly here, this will make `gradle` report gradle version and quit.

2022-09-01 15:22 UTC, t0yv0 approved these changes
Looks better thank you.

2022-09-01 19:15 UTC, merged