[provider] Fix OIDC support
pulumi/pulumi-azure-native pull request #2086
Opened 2022-11-21 21:01 UTC by pgavlin

Add parameters to the client configuration used by the provider so that the provider supports OIDC authentication.

2022-11-21 21:57 UTC, jaxxstorm commented
Fixes #1324

2022-11-25 17:41 UTC, stefanhenseler commented
@pgavlin awesome! Just the issue I started running into a couple of days ago. Any Idea when this will be released?

2022-12-02 10:45 UTC, danielrbradley requested changes
This depends on moving the core authentication library from ADAL to MSAL. @thomas11 has [made good progress](https://github.com/pulumi/pulumi-azure-native/pull/1942) in this area but there's still more investment needed to get it over the line yet.

2022-12-02 10:54 UTC, danielrbradley commented
Feel free to close this @pgavlin and we'll re-integrate this work once the core auth libray has been upgraded

2023-02-10 00:22 UTC, illusional commented
Any luck on this front, would be awesome to use MSI w/ workload identity federation support with Pulumi!

2023-02-10 03:02 UTC, thomas11 commented
> Any luck on this front, would be awesome to use MSI w/ workload identity federation support with Pulumi!

Hi @illusional, there are some complications to work through, but the good news is we're working on it.

2023-03-31 20:50 UTC, thomas11 commented
superseded by #2320

2023-03-31 20:50 UTC, closed without merging