Remove new preview API versions
pulumi/pulumi-azure-native pull request #2295
Opened 2023-03-10 17:08 UTC by danielrbradley

Hopefully fixes https://github.com/pulumi/pulumi-azure-native/issues/2294

- Add mechanism for removing specific API verisons
- Curate preview versions added since the last provider release - so this shouldn't be a breaking change.

2023-03-10 17:12 UTC, danielrbradley commented
Pre-release publish run to see if we're addressed the NPM limit: https://github.com/pulumi/pulumi-azure-native/actions/runs/4386814547

2023-03-10 18:10 UTC, squaremo requested changes
The entry for `SecurityFabric` in removed.json does not seem to have resulted in it being removed: https://github.com/pulumi/pulumi-azure-native/tree/reduce-sdk-size/sdk/dotnet/ServiceFabric/V20230201Preview

2023-03-10 19:12 UTC, danielrbradley commented on provider/pkg/openapi/discover.go
> +		if removed[providerName] != nil {
Perhaps, what impact does it have?

2023-03-13 09:14 UTC, danielrbradley commented
@squaremo are these really blocking changes? This seems pretty urgent to get merged so would prefer not having to go round another loop of CI for trivialities.

2023-03-13 09:15 UTC, danielrbradley commented on provider/pkg/openapi/versioner.go
> +	deprecatedPath := filepath.Join(dir, "versions", "removed.json")
Just a refactoring left-over

2023-03-13 10:00 UTC, merged

2023-03-13 10:00 UTC, squaremo commented
> are these really blocking changes?

Not the change of variable name, and the map presence test -- those were me forgetting I'd made the comments when I clicked "request changes". Sorry about that.

But the removal code apparently not removing one of the specified APIs needs investigation, I think. Am I misinterpreting what it does?