Fix go tests
pulumi/pulumi-azure-native pull request #2473
Opened 2023-05-25 13:18 UTC by danielrbradley

2023-05-31 18:28 UTC, kpitzen commented on Makefile
> +export GOWORK := off
SHOULD be a noop in ci, but is this intentional for everyone else?

2023-05-31 19:16 UTC, thomas11 approved these changes

2023-05-31 19:16 UTC, thomas11 commented on Makefile
> +export GOWORK := off
IMO, when in doubt, consistency wins.

2023-05-31 22:16 UTC, thomas11 commented on Makefile
> +export GOWORK := off
Although, it just occurred to me that a remark in CONTRIBUTING could be helpful to prevent confusion for people who have workspaces set up.

2023-06-01 06:50 UTC, mikhailshilkov requested changes
Please add a PR description according to our [standards](https://docs.google.com/document/d/1QG5f95vWtBNI7EuQ3kgBlyFtMJKSCeN0AGqYPosV9lg/edit). This helps others review the PR now and later down the line. Thank you!

2023-06-01 06:52 UTC, mikhailshilkov commented on .github/workflows/dev-version.yml
> +          # TODO: Remove after v2 release
Let's make sure we open an issue for every TODO in code, and reference that issue from the TODO

> Added TODOs must include links to issue numbers in TODO[pulumi/pulumi#7973] format.

2023-06-01 14:00 UTC, merged