Fix timeout handling in example program gen
pulumi/pulumi-azure-native pull request #2635
Opened 2023-08-04 11:16 UTC by thomas11

The previous approach using `defer` did not work in my local testing.
I believe that is because the panic occurs in another goroutine than
`recover`.

This approach is a standard technique, described e.g. in
https://gobyexample.com/timeouts.

2023-08-07 09:57 UTC, mikhailshilkov commented
@thomas11 Could you please open (or find?) a corresponding issue with problem description and link it to the PR? Thank you!

2023-08-13 21:23 UTC, thomas11 commented
@mikhailshilkov done.
Fixes #2650

2023-08-16 19:46 UTC, rquitales commented on provider/pkg/gen/examples.go
> +	c := make(chan programGenResult, 1)
I might have opted to just use an error channel here to avoid needing to create a struct object since we're already using named return vars, but that might make the code harder to read/follow.

2023-08-16 19:47 UTC, rquitales approved these changes
LGTM. The previous implementation would have failed since the panic occurs in a separate goroutine.

2023-08-16 19:51 UTC, thomas11 commented on provider/pkg/gen/examples.go
> +	c := make(chan programGenResult, 1)
Ah, an inverse approach where the happy path happens inside the Goroutine and the error handling outside, if an error is sent through the channel?

2023-08-16 20:05 UTC, rquitales commented on provider/pkg/gen/examples.go
> +	c := make(chan programGenResult, 1)
Something like this is what I was thinking of (don't even need an error channel actually):
```
func recoverableProgramGen(name string, program *hcl2.Program, fn programGenFn) (files map[string][]byte, err error) {
...
done := make(chan struct{}, 1)
go func() {
		var d hcl.Diagnostics
                 // files will be returned due to named return variable
		files, d, err = fn(program)
                 if err != nil {
                        // err is assignined to the named return error variable, so no need to explicitly handle
                        done <- struct{}{}
                 }
		if d.HasErrors() {
			err = program.NewDiagnosticWriter(os.Stderr, 0, true).WriteDiagnostics(res.d)
			if err != nil {
				log.Printf("failed to write diagnostics: %v", err)
			}
		}
                 done <- struct{}{}
	}()
select {
case <-done:
    break
case <- time.After(3 * time.Minute):
    log.Printf("%s timed out after 3m", name)
    break
}
```

2023-08-16 20:10 UTC, rquitales requested changes

2023-08-16 20:10 UTC, rquitales commented on provider/pkg/gen/examples.go
> +		log.Printf("%s timed out after 3m", name)
On a second pass, do we actually want to return an error if it timed out?

2023-08-18 07:13 UTC, thomas11 commented on provider/pkg/gen/examples.go
> +		log.Printf("%s timed out after 3m", name)
you're right, good catch

2023-08-18 19:06 UTC, rquitales approved these changes

2023-08-21 10:02 UTC, merged