Detect and prevent clashing different types under the same name
pulumi/pulumi-azure-native pull request #678
Opened 2021-03-18 14:55 UTC by mikhailshilkov

2021-03-18 16:12 UTC, lblackstone requested changes
Looks good overall. Just a few comments

2021-03-18 16:12 UTC, lblackstone commented on provider/pkg/gen/schema.go
> +func compatibleTypes(t1 schema.ComplexTypeSpec, t2 schema.ComplexTypeSpec, isOutput bool) error {
It might be good to include information about what to update to fix these types of errors (i.e. update `typeNameOverride`)

2021-03-18 16:12 UTC, lblackstone commented on provider/pkg/gen/schema.go
> +	"SecurityInsights.WatchlistItem.UserInfo": "WatchlistUserInfo",
Are these both supposed to map to `WatchlistUserInfo`?

2021-03-18 16:12 UTC, lblackstone commented on provider/pkg/openapi/discover.go
> +
You should be able to simplify this by compiling the regexs directly in the variable declaration rather than splitting the string definition and compile steps. Something like this:

```
var regexs = []*regexp.Regexp{
	regexp.MustCompile("foo"),
	regexp.MustCompile("bar"),
}
```

2021-03-18 16:12 UTC, lblackstone commented on provider/pkg/openapi/discover.go
> +var legacyPathMappingNormalized = map[string]string{}
Same here; you can initialize the map directly in the variable declaration.

2021-03-18 16:12 UTC, lblackstone commented on provider/pkg/openapi/versioner.go
> +	// This preview version introduces new resources but also changes the shape of some times, so merging it with
s/times/items

2021-03-18 16:12 UTC, lblackstone commented on provider/pkg/openapi/versioner.go
> +var deprecatedResources = map[string]bool {
Any reason not to use a StringSet here?

2021-03-18 16:15 UTC, mikhailshilkov commented on provider/pkg/gen/schema.go
> +	"SecurityInsights.WatchlistItem.UserInfo": "WatchlistUserInfo",
Yes, both resources use the same type

2021-03-19 09:31 UTC, mikhailshilkov commented on provider/pkg/openapi/versioner.go
> +var deprecatedResources = map[string]bool {
No... changed now

2021-03-19 09:31 UTC, mikhailshilkov commented on provider/pkg/openapi/discover.go
> +
Done, thank you

2021-03-19 09:32 UTC, mikhailshilkov commented on provider/pkg/openapi/discover.go
> +var legacyPathMappingNormalized = map[string]string{}
This one is a bit trickier as I need to call `normalizePath` on every key and every value. I guess I don't want to explicitly add this call 30 times. Or is there a better way?

2021-03-19 09:35 UTC, mikhailshilkov commented on provider/pkg/gen/schema.go
> +func compatibleTypes(t1 schema.ComplexTypeSpec, t2 schema.ComplexTypeSpec, isOutput bool) error {
Extended the comment

2021-03-19 15:53 UTC, lblackstone commented on provider/pkg/openapi/discover.go
> +var legacyPathMappingNormalized = map[string]string{}
Ah, didn't notice the `normalizePath` call before. I suppose you might be able to precompute the normalization and directly initialize the normalized map, but this works too.

2021-03-19 15:53 UTC, lblackstone approved these changes

2021-03-19 16:41 UTC, mikhailshilkov commented on provider/pkg/openapi/discover.go
> +var legacyPathMappingNormalized = map[string]string{}
I want to keep the original URLs in code so that they are easily searchable in the Open API specs

2021-03-19 17:15 UTC, viveklak approved these changes

2021-03-19 20:08 UTC, merged